import { PERMISSIONS } from './permissions';

export const ROLES = {
  ADMIN: 'super_admin',
  TEACHER: 'guru',
  STUDENT: 'student',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SISWA_VIEW,
    PERMISSIONS.SISWA_CREATE,
    PERMISSIONS.SISWA_EDIT,
    PERMISSIONS.SISWA_DELETE,
    PERMISSIONS.GURU_VIEW,
    PERMISSIONS.GURU_CREATE,
    PERMISSIONS.GURU_EDIT,
    PERMISSIONS.GURU_DELETE,
    PERMISSIONS.KELAS_VIEW,
    PERMISSIONS.KELAS_CREATE,
    PERMISSIONS.KELAS_EDIT,
    PERMISSIONS.KELAS_DELETE,
    PERMISSIONS.MAPEL_VIEW,
    PERMISSIONS.MAPEL_CREATE,
    PERMISSIONS.MAPEL_EDIT,
    PERMISSIONS.MAPEL_DELETE,
    PERMISSIONS.JADWAL_VIEW,
    PERMISSIONS.JADWAL_CREATE,
    PERMISSIONS.JADWAL_EDIT,
    PERMISSIONS.JADWAL_DELETE,
    PERMISSIONS.ABSENSI_VIEW,
    PERMISSIONS.ABSENSI_INPUT,
    PERMISSIONS.LAPORAN_VIEW,
    PERMISSIONS.LAPORAN_EXPORT
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SISWA_VIEW,
    PERMISSIONS.KELAS_VIEW,
    PERMISSIONS.MAPEL_VIEW,
    PERMISSIONS.JADWAL_VIEW,
    PERMISSIONS.ABSENSI_VIEW,
    PERMISSIONS.ABSENSI_INPUT,
    PERMISSIONS.LAPORAN_VIEW
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.ABSENSI_SCAN,
    PERMISSIONS.PROFIL_VIEW
  ]
};
