export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  STUDENTS: '/siswa',
  TEACHERS: '/guru',
  CLASSES: '/kelas',
  SUBJECTS: '/mapel',
  SCHEDULES: '/jadwal',
  ATTENDANCE: '/absensi',
  REPORTS: '/laporan',
  PROFILE: '/profil',
  SETTINGS: '/settings',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
};
