export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  
  SISWA_VIEW: 'siswa.view',
  SISWA_CREATE: 'siswa.create',
  SISWA_EDIT: 'siswa.edit',
  SISWA_DELETE: 'siswa.delete',
  
  GURU_VIEW: 'guru.view',
  GURU_CREATE: 'guru.create',
  GURU_EDIT: 'guru.edit',
  GURU_DELETE: 'guru.delete',
  
  KELAS_VIEW: 'kelas.view',
  KELAS_CREATE: 'kelas.create',
  KELAS_EDIT: 'kelas.edit',
  KELAS_DELETE: 'kelas.delete',
  
  MAPEL_VIEW: 'mapel.view',
  MAPEL_CREATE: 'mapel.create',
  MAPEL_EDIT: 'mapel.edit',
  MAPEL_DELETE: 'mapel.delete',
  
  JADWAL_VIEW: 'jadwal.view',
  JADWAL_CREATE: 'jadwal.create',
  JADWAL_EDIT: 'jadwal.edit',
  JADWAL_DELETE: 'jadwal.delete',
  
  ABSENSI_VIEW: 'absensi.view',
  ABSENSI_INPUT: 'absensi.input',
  ABSENSI_SCAN: 'absensi.scan',
  
  LAPORAN_VIEW: 'laporan.view',
  LAPORAN_EXPORT: 'laporan.export',

  PROFIL_VIEW: 'profil.view'
};

export const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SISWA_VIEW,
    PERMISSIONS.SISWA_CREATE,
    PERMISSIONS.SISWA_EDIT,
    PERMISSIONS.SISWA_DELETE,
    PERMISSIONS.GURU_VIEW,
    PERMISSIONS.GURU_CREATE,
    PERMISSIONS.GURU_EDIT,
    PERMISSIONS.GURU_DELETE,
    PERMISSIONS.KELAS_VIEW,
    PERMISSIONS.KELAS_CREATE,
    PERMISSIONS.KELAS_EDIT,
    PERMISSIONS.KELAS_DELETE,
    PERMISSIONS.MAPEL_VIEW,
    PERMISSIONS.MAPEL_CREATE,
    PERMISSIONS.MAPEL_EDIT,
    PERMISSIONS.MAPEL_DELETE,
    PERMISSIONS.JADWAL_VIEW,
    PERMISSIONS.JADWAL_CREATE,
    PERMISSIONS.JADWAL_EDIT,
    PERMISSIONS.JADWAL_DELETE,
    PERMISSIONS.ABSENSI_VIEW,
    PERMISSIONS.ABSENSI_INPUT,
    PERMISSIONS.LAPORAN_VIEW,
    PERMISSIONS.LAPORAN_EXPORT
  ],
  guru: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SISWA_VIEW,
    PERMISSIONS.KELAS_VIEW,
    PERMISSIONS.MAPEL_VIEW,
    PERMISSIONS.JADWAL_VIEW,
    PERMISSIONS.ABSENSI_VIEW,
    PERMISSIONS.ABSENSI_INPUT,
    PERMISSIONS.LAPORAN_VIEW
  ],
  student: [
    PERMISSIONS.ABSENSI_SCAN,
    PERMISSIONS.PROFIL_VIEW
  ]
};
