/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAcademicYearsRouteImport } from './routes/dashboard/academic-years'
import { Route as DashboardAttendanceRecapRouteImport } from './routes/dashboard/attendance-recap'
import { Route as DashboardClassroomsRouteImport } from './routes/dashboard/classrooms'
import { Route as DashboardRoomsRouteImport } from './routes/dashboard/rooms'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard/students'
import { Route as DashboardSubjectsRouteImport } from './routes/dashboard/subjects'
import { Route as DashboardTeachersRouteImport } from './routes/dashboard/teachers'
import { Route as DashboardAttendanceRecapStudentIdRouteImport } from './routes/dashboard/attendance-recap.$studentId'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings.index'
import { Route as DashboardSettingsPublicHolidaysRouteImport } from './routes/dashboard/settings.public-holidays'
import { Route as DashboardSettingsSchoolZonesRouteImport } from './routes/dashboard/settings.school-zones'
import { Route as DashboardTeacherStudentsRouteImport } from './routes/dashboard/teacher/students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_auth/login.lazy').then((d) => d.Route))
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAcademicYearsRoute = DashboardAcademicYearsRouteImport.update({
  id: '/academic-years',
  path: '/academic-years',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRecapRoute =
  DashboardAttendanceRecapRouteImport.update({
    id: '/attendance-recap',
    path: '/attendance-recap',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClassroomsRoute = DashboardClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoomsRoute = DashboardRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubjectsRoute = DashboardSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeachersRoute = DashboardTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRecapStudentIdRoute =
  DashboardAttendanceRecapStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => DashboardAttendanceRecapRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsPublicHolidaysRoute =
  DashboardSettingsPublicHolidaysRouteImport.update({
    id: '/public-holidays',
    path: '/public-holidays',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsSchoolZonesRoute =
  DashboardSettingsSchoolZonesRouteImport.update({
    id: '/school-zones',
    path: '/school-zones',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardTeacherStudentsRoute =
  DashboardTeacherStudentsRouteImport.update({
    id: '/teacher/students',
    path: '/teacher/students',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/dashboard/academic-years': typeof DashboardAcademicYearsRoute
  '/dashboard/attendance-recap': typeof DashboardAttendanceRecapRouteWithChildren
  '/dashboard/classrooms': typeof DashboardClassroomsRoute
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/attendance-recap/$studentId': typeof DashboardAttendanceRecapStudentIdRoute
  '/dashboard/settings/public-holidays': typeof DashboardSettingsPublicHolidaysRoute
  '/dashboard/settings/school-zones': typeof DashboardSettingsSchoolZonesRoute
  '/dashboard/teacher/students': typeof DashboardTeacherStudentsRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard/academic-years': typeof DashboardAcademicYearsRoute
  '/dashboard/attendance-recap': typeof DashboardAttendanceRecapRouteWithChildren
  '/dashboard/classrooms': typeof DashboardClassroomsRoute
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/attendance-recap/$studentId': typeof DashboardAttendanceRecapStudentIdRoute
  '/dashboard/settings/public-holidays': typeof DashboardSettingsPublicHolidaysRoute
  '/dashboard/settings/school-zones': typeof DashboardSettingsSchoolZonesRoute
  '/dashboard/teacher/students': typeof DashboardTeacherStudentsRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/dashboard/academic-years': typeof DashboardAcademicYearsRoute
  '/dashboard/attendance-recap': typeof DashboardAttendanceRecapRouteWithChildren
  '/dashboard/classrooms': typeof DashboardClassroomsRoute
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/attendance-recap/$studentId': typeof DashboardAttendanceRecapStudentIdRoute
  '/dashboard/settings/public-holidays': typeof DashboardSettingsPublicHolidaysRoute
  '/dashboard/settings/school-zones': typeof DashboardSettingsSchoolZonesRoute
  '/dashboard/teacher/students': typeof DashboardTeacherStudentsRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/academic-years'
    | '/dashboard/attendance-recap'
    | '/dashboard/classrooms'
    | '/dashboard/rooms'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/teachers'
    | '/dashboard/'
    | '/dashboard/attendance-recap/$studentId'
    | '/dashboard/settings/public-holidays'
    | '/dashboard/settings/school-zones'
    | '/dashboard/teacher/students'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/academic-years'
    | '/dashboard/attendance-recap'
    | '/dashboard/classrooms'
    | '/dashboard/rooms'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/teachers'
    | '/dashboard'
    | '/dashboard/attendance-recap/$studentId'
    | '/dashboard/settings/public-holidays'
    | '/dashboard/settings/school-zones'
    | '/dashboard/teacher/students'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/_auth/login'
    | '/dashboard/academic-years'
    | '/dashboard/attendance-recap'
    | '/dashboard/classrooms'
    | '/dashboard/rooms'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/teachers'
    | '/dashboard/'
    | '/dashboard/attendance-recap/$studentId'
    | '/dashboard/settings/public-holidays'
    | '/dashboard/settings/school-zones'
    | '/dashboard/teacher/students'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/academic-years': {
      id: '/dashboard/academic-years'
      path: '/academic-years'
      fullPath: '/dashboard/academic-years'
      preLoaderRoute: typeof DashboardAcademicYearsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance-recap': {
      id: '/dashboard/attendance-recap'
      path: '/attendance-recap'
      fullPath: '/dashboard/attendance-recap'
      preLoaderRoute: typeof DashboardAttendanceRecapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classrooms': {
      id: '/dashboard/classrooms'
      path: '/classrooms'
      fullPath: '/dashboard/classrooms'
      preLoaderRoute: typeof DashboardClassroomsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rooms': {
      id: '/dashboard/rooms'
      path: '/rooms'
      fullPath: '/dashboard/rooms'
      preLoaderRoute: typeof DashboardRoomsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subjects': {
      id: '/dashboard/subjects'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof DashboardSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teachers': {
      id: '/dashboard/teachers'
      path: '/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof DashboardTeachersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance-recap/$studentId': {
      id: '/dashboard/attendance-recap/$studentId'
      path: '/$studentId'
      fullPath: '/dashboard/attendance-recap/$studentId'
      preLoaderRoute: typeof DashboardAttendanceRecapStudentIdRouteImport
      parentRoute: typeof DashboardAttendanceRecapRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/public-holidays': {
      id: '/dashboard/settings/public-holidays'
      path: '/public-holidays'
      fullPath: '/dashboard/settings/public-holidays'
      preLoaderRoute: typeof DashboardSettingsPublicHolidaysRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/school-zones': {
      id: '/dashboard/settings/school-zones'
      path: '/school-zones'
      fullPath: '/dashboard/settings/school-zones'
      preLoaderRoute: typeof DashboardSettingsSchoolZonesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/teacher/students': {
      id: '/dashboard/teacher/students'
      path: '/teacher/students'
      fullPath: '/dashboard/teacher/students'
      preLoaderRoute: typeof DashboardTeacherStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardAttendanceRecapRouteChildren {
  DashboardAttendanceRecapStudentIdRoute: typeof DashboardAttendanceRecapStudentIdRoute
}

const DashboardAttendanceRecapRouteChildren: DashboardAttendanceRecapRouteChildren =
  {
    DashboardAttendanceRecapStudentIdRoute:
      DashboardAttendanceRecapStudentIdRoute,
  }

const DashboardAttendanceRecapRouteWithChildren =
  DashboardAttendanceRecapRoute._addFileChildren(
    DashboardAttendanceRecapRouteChildren,
  )

interface DashboardSettingsRouteChildren {
  DashboardSettingsPublicHolidaysRoute: typeof DashboardSettingsPublicHolidaysRoute
  DashboardSettingsSchoolZonesRoute: typeof DashboardSettingsSchoolZonesRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsPublicHolidaysRoute: DashboardSettingsPublicHolidaysRoute,
  DashboardSettingsSchoolZonesRoute: DashboardSettingsSchoolZonesRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAcademicYearsRoute: typeof DashboardAcademicYearsRoute
  DashboardAttendanceRecapRoute: typeof DashboardAttendanceRecapRouteWithChildren
  DashboardClassroomsRoute: typeof DashboardClassroomsRoute
  DashboardRoomsRoute: typeof DashboardRoomsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardSubjectsRoute: typeof DashboardSubjectsRoute
  DashboardTeachersRoute: typeof DashboardTeachersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTeacherStudentsRoute: typeof DashboardTeacherStudentsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAcademicYearsRoute: DashboardAcademicYearsRoute,
  DashboardAttendanceRecapRoute: DashboardAttendanceRecapRouteWithChildren,
  DashboardClassroomsRoute: DashboardClassroomsRoute,
  DashboardRoomsRoute: DashboardRoomsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardSubjectsRoute: DashboardSubjectsRoute,
  DashboardTeachersRoute: DashboardTeachersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTeacherStudentsRoute: DashboardTeacherStudentsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
