name: Node.js CI

on:
  push:
    branches: [ development, staging ]
  pull_request:
    branches: [ development, staging ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repositori
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Node.js lingkungan kerja
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # 4. Jalankan Linter (ESLint)
      #- name: Run Linter
      #  run: npm run lint

      # 5. Jalankan Pengujian (Vitest)
      - name: Run Vitest
        run: npx vitest run

      # 6. Build aplikasi React + Vite
      - name: Build Application
        run: npm run build

      # 7. Simpan folder dist hasil build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-build
          path: dist/
